[project]
name = "podomoro-bot"
version = "0.1.0"
description = "Podomoro Bot Codes"
readme = "README.md"
requires-python = "==3.11.13"
dependencies = [
    "pandas>=2.3.3",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "ultralytics>=8.3.216",
]
